PhpcsChanged/Cli.php
PhpcsChanged/PhpcsMessages.php
config.yml
tests/PhpcsChangedTest.php
tests/PhpcsMessagesTest.php

Currently if you run the CLI command `phpcs-changed` using the `--svn` option on a just-added file (one with no svn history), then you will get an error.
This PR changes the behavior such that it handles those files correctly, reporting all phpcs errors.

Support new files in svn workflow

---

PhpcsChanged/Cli.php
PhpcsChanged/NonFatalException.php
PhpcsChanged/PhpcsMessages.php
PhpcsChanged/ShellOperator.php
PhpcsChanged/SvnWorkflow.php
PhpcsChanged/UnixShell.php
PhpcsChanged/Version.php
bin/phpcs-changed
index.php
tests/SvnWorkflowTest.php

This refactors the svn workflow functionality so that it can be tested and adds unit tests for each part.

Add tests for svn workflow

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
PhpcsChanged/ShellException.php
PhpcsChanged/ShellOperator.php
PhpcsChanged/SvnWorkflow.php
PhpcsChanged/UnixShell.php
README.md
bin/phpcs-changed
index.php
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

This adds a `--git` CLI shortcut and a git workflow to automatically collect the three necessary pieces of data for a git-versioned file in the same way that the `--svn` shortcut does for svn-versioned files.
Fixes #3

Add git workflow

---

PhpcsChanged/GitWorkflow.php
PhpcsChanged/SvnWorkflow.php
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

When a newly added file is empty, then the command `cat filename.php | phpcs` fails with the error `You must supply at least one file or directory to process`. In that case, however, we know there are no phpcs errors so we can just skip that command.
Fixes #5

Handle empty vcs files

---

PhpcsChanged/GitWorkflow.php
PhpcsChanged/SvnWorkflow.php
README.md

While the quiet mode in PHPCS is the default setting, it can be changed via `show_progress` config. Turning the `show_progress` on / disabling the quiet mode, makes the PHPCS to not only output the JSON contianing warnings and errors, but also a progress on individual files (eg.: `E 1 / 1 (100%)`), which then breaks the phpcs-changed's JSON parsing.
By using the `-q` flag in the `phpcs --format=json` commands, we would force the quiet mode for phpcs-changed run commands only, not affecting local settings, and making sure the phpcs-changed works no matter what the local setting is.
Fixes #7

Force quiet mode

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
PhpcsChanged/NoChangesException.php
PhpcsChanged/SvnWorkflow.php
index.php
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

Previously unchanged files caused a `NonFatalException` which allowed
the linter to skip them and move on to the next file. This was done
under the assumption that running the linter on such files was done by
mistake, since by definition they have no changed lines.
However, this behavior denies the Reporter the opportunity to make that
decision itself.
It can also be confusing when run on _only_ unchanged files because in
those cases even with the JSON reporter, no output is produced and no
error code is set.
With this diff, unchanged files will be treated simply has having no
phpcs messages, and the Reporter can decide how best to deal with that.

Treat unchanged files as normal

---

.circleci/config.yml
composer.json

This downgrades the required PHP version to 7.1 from 7.2. I'm not certain why I chose 7.2 in the first place. There doesn't seem to be any dependencies that would need that version and I don't believe I used any 7.2-specific features.

Downgrade PHP requirement to 7.1

---

PhpcsChanged/GitWorkflow.php
PhpcsChanged/SvnWorkflow.php

By passing in the file name via `--stdin-path` argument, we make the `<exclude-pattern>` and `<include-patter>` configs in ruleset.xml working properly.
Without passing in the file path, PHPCS does not know with what file it's currently working, so can't properly apply those.

Add --stdin-path argument to phpcs command

---

README.md

Since CLI usage is arguably more common, this brings it up to the top and makes it more clear how it works.

Update readme to make it easier to see CLI usage

---

PhpcsChanged/Cli.php
PhpcsChanged/FullReporter.php
PhpcsChanged/JsonReporter.php
PhpcsChanged/PhpcsMessages.php
README.md
bin/phpcs-changed
composer.json
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

Currently `phpcs-changed` operates only on one file at a time, but there's no good reason for this. This PR modifies the tool to be able to run on a list of files, both via the API and on the command-line.

Allow processing multiple files at once

---

PhpcsChanged/FullReporter.php
PhpcsChanged/JsonReporter.php

This prevents the reporters displaying the output of a single file multiple times if there are multiple errors.

Make sure to only include one of each file in reporters

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
README.md
bin/phpcs-changed
tests/GitWorkflowTest.php

Git mode has a few issues which this PR should improve.
- You'll be able to run `phpcs-changed --git` on a file when you are not in the git root directory.
- You'll be able to specify `--git-staged` or `--git-unstaged` to compare staged or unstaged changes, respectively.

Improve git mode

---

PhpcsChanged/Cli.php
PhpcsChanged/FullReporter.php
PhpcsChanged/JsonReporter.php
PhpcsChanged/PhpcsMessage.php
PhpcsChanged/PhpcsMessages.php
PhpcsChanged/Reporter.php
README.md
bin/phpcs-changed

This adds the `-s` option available on phpcs to phpcs-changed.

Add show sniff codes option

---

bin/phpcs-changed

The current implementation via glob ignores .php files in current dir in case `.` is passed as file list, and also ignores nested directories.
To fix the issue, this commit introduces a more solid implementation via `RecursiveDirectoryIterator` with appropriate filtering.
The issue can be demonstrated when running the phpcs-changed eg.: for the [liveblog](https://github.com/Automattic/liveblog) plugin from within the root directory of the plugin. In such case, the following files are ignored:
```
./liveblog.php
./templates/amp/feed.ph
./templates/amp/pagination.ph
./templates/amp/entry.php
./templates/amp/author.php
```

Fix the filenames expasions

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
PhpcsChanged/ShellOperator.php
PhpcsChanged/SvnWorkflow.php
PhpcsChanged/UnixShell.php
bin/phpcs-changed
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

When phpcs-changed is used in CI (eg.: Travis), there is no good way to determine the unified diff, since the working directory is clean.
In order to accommodate the situation when a branch or PR is being checked, a support for inter branch diff is helpful.
This PR adds a new param `git-branch:` which instructs the phpcs-changed to run a diff of the current working directory against specified branch (eg.: `master`).
A usage in Travis would be, for instance, as follows:
```
script:
- if [[ "$SNIFF" == "1" ]] && [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then /tmp/phpcs-changed/bin/phpcs-changed --git --git-branch "$TRAVIS_BRANCH" --standard="WordPress-VIP-Go" .; fi
```
For the needs of checking whether a file is a new one, the `UnixShell::executeCommand` method had to be changed to use …

Add support for inter branch diffs

---

PhpcsChanged/Cli.php
bin/phpcs-changed
tests/CliTest.php

PHPCS which is internally used by the phpcs-changed allows more than .php files to be linted by default. This PR brings the default allowed extensions in phpcs-changed on par with phpcs.
The logic is a copy-paste from the phpcs, as it would validate the extensions using the very same logic again, so it should ideally work the same in both places.
Fixes #27

Allow more files extensions to be checked

---

tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php
tests/helpers/Functions.php
tests/helpers/TestShell.php
tests/helpers/helpers.php

While working on the other PRs, I found it unnecessarily verbose to write an integration test.
Feels like it could be made easier and less error-prone (eg: having the class to throw an exception by default in case unknown command is run) in case the project would provide some helpers. Eg.: a TestShell class, which would do the heavy lifting, while letting the developer to only focus on registering the commands.
In the PR I'm also adding a test debug function implementation, which can be shared across the tests, again minimising the amount of code developer has to write (including the PHPCS exclusion comment).
Please, take this only as a proposal, and feel free to say "No" if you don't see the fit here :)

Introduce TestShell for making it easier to introduce new tests

---

PhpcsChanged/DiffLineMap.php
tests/GitWorkflowTest.php

In case the interbranch git diff is used, the diff provided by git contains /dev/null instead of a real filename on the --- line when the file does not exist in the other branch.
I don't think that there was any specific reason to use the --- filename, insteand of the +++.

Fix filename detection

---

PhpcsChanged/Cli.php
README.md
bin/phpcs-changed
tests/CliTest.php

PHPCS has an ignore option which allows developers to skip certain directories or files, specified via patterns.
In order to be able to use phpcs-changed as a drop-in replacement for phpcs, phpcs-changed should have the `--ignore` options which works similarly to the one in phpcs.
This PR introduces a `shouldIgnorePath` function, which follows the same logic the phpcs does when it's filtering the files (the function body is mostly a copy-paste of the original).
Part of the #26 .

Add the ignore option and tests

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
tests/GitWorkflowTest.php

When using the various git modes, the way to determine the contents of the "new" version of a file differs. Using `git-unstaged`, we can `cat` the working copy of the file; using `git-staged`, we must ask git for the staged version; using `git-branch`, we must ask git for the committed version.
An oversight in https://github.com/sirbrillig/phpcs-changed/pull/18 meant that the first two modes used the current working copy of the file. This PR fixes that bug by using the staged version for `git-staged`.
The third mode is a little more complicated. https://github.com/sirbrillig/phpcs-changed/pull/28 added the `git-branch` mode, and based on the description, it was intended to also use the current working copy of the file. However, in https://github.com/sirbrillig/phpcs-changed/pull/31 and …

Use different commands for new files based on git mode

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
README.md
bin/phpcs-changed
tests/GitWorkflowTest.php

Introduces `--git-base-object`, which is accidentally compatible with the
current `--git-branch` implementation. Merge them as to make the behavior
official

git-base-object

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
tests/GitWorkflowTest.php

When `--git-base` is used, we use `git diff $BASE...` to fetch the diff,
which will diff against the merge-base of $BASE and HEAD rather than
against $BASE itself.
When we run phpcs for the old file versions, we run it against the
version from $BASE itself rather than the merge-base version.
Since the diff does not match the versions of the files used to produce
the phpcs output, the line number correction may fail and unchanged
issues may be incorrectly reported.
This PR adds an initial step that replaces the passed --git-base with
the merge-base commit hash so later steps use the correct file versions.
Fixes #42

Fetch correct old file versions

---

PhpcsChanged/CacheEntry.php
PhpcsChanged/CacheInterface.php
PhpcsChanged/CacheManager.php
PhpcsChanged/Cli.php
PhpcsChanged/FileCache.php
PhpcsChanged/GitWorkflow.php
PhpcsChanged/PhpcsMessages.php
PhpcsChanged/ShellOperator.php
PhpcsChanged/UnixShell.php
README.md
bin/phpcs-changed
index.php
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php
tests/helpers/GitFixture.php
tests/helpers/PhpcsFixture.php
tests/helpers/SvnFixture.php
tests/helpers/TestCache.php
tests/helpers/TestShell.php
tests/helpers/helpers.php

Running phpcs is probably the largest overhead of using phpcs-changed, since it needs to be run twice for each file. In addition, just getting the contents of some of those files can be expensive, notably old versions of svn files. In this PR we cache each phpcs result for later use. Each cache entry is removed if the svn revision changes (for svn mode), or if the file hash of any file changes. We keep caches for different phpcs standards so that phpcs-changed can be run on the same file for different standards multiple times and still benefit from the cache.
This PR adds caching to svn mode and git mode. To activate the cache, you must use the `--cache` CLI option, and it can be explicitly disabled using `--no-cache`. The cache can be completely cleared by using the `--clear-cache` …

Add caching of phpcs results

---

PhpcsChanged/CacheInterface.php
PhpcsChanged/CacheManager.php
PhpcsChanged/CacheObject.php
PhpcsChanged/FileCache.php
index.php
tests/helpers/TestCache.php

Cache interfaces shouldn't need to know the internal workings of the `CacheManager`, nor have direct access to it. That's a leaky abstraction. They should just be concerned with saving the state of the cache to storage and loading it again.
In this PR I introduce a value object for the state of the cache, called `CacheObject`. Mostly it's a collection of `CacheEntry` objects but there's also a few metadata values which are kept by the state: `revisionId` and `cacheVersion`. Each cache interface now just has to persist a `CacheObject` and return one. If more cache interfaces are introduced in the future, this should greatly simplify their APIs.

Refactor CacheInterface so that it deals only with a value object

---

PhpcsChanged/CacheManager.php
PhpcsChanged/CacheObject.php
PhpcsChanged/Cli.php
PhpcsChanged/FileCache.php
PhpcsChanged/SvnWorkflow.php
tests/SvnWorkflowTest.php
tests/helpers/Functions.php
tests/helpers/SvnFixture.php
tests/helpers/TestCache.php

Previously we were invalidating the whole cache for svn files whenever the svn revision changed, but this is overly broad. Most files of a repo will not change when the revision changes, and we should be able to use their cached versions.
This PR changes the cache so that it uses the file's last changed revision as the hash for that file, and does not clear the whole cache based on revision.

Cache svn previous file by last changed version

---

PhpcsChanged/Cli.php
README.md
bin/phpcs-changed

When using futures in arcanist linter, the external lint program, eg.: phpcs-changed in this case, should always return 0 status, even if there are lint errors, otherwise the external program's run is considered being unsuccessful.

Always return 0 from reportMessagesAndExit when run with --arc-lint flag

---

PhpcsChanged/Cli.php
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

When there are no linting issues reported by PHPCS in the new file, there is no point in checking the orig verion, since we would not report any issues anyway.
This should speed up the phpcs-changed for files w/o lint issues.
props to @sirbrillig for the idea.

Only run orig file PHPCS linting when the new version has lint issues

---

PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
PhpcsChanged/ShellOperator.php
PhpcsChanged/UnixShell.php
README.md
bin/phpcs-changed
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php
tests/helpers/TestShell.php

This is a follow-up to #51, which modifies the automatic mode workflows so that they do not run phpcs on the previous version of a file if the current version has no phpcs messages; in this PR we modify them further to also not generate a VCS diff of the file in that case.
Fixes https://github.com/sirbrillig/phpcs-changed/issues/53
To do:

Do not fetch file diff if updated file has no messages

---

PhpcsChanged/CacheManager.php
PhpcsChanged/Cli.php
PhpcsChanged/GitWorkflow.php
PhpcsChanged/LintMessages.php
PhpcsChanged/SvnWorkflow.php
PhpcsChanged/functions.php
README.md
bin/phpcs-changed

This updates the terminology used by the code (without changing any user-facing terms or APIs) to standardize terminology of the previous version of a file and the changed version of a file as **"unmodified"** and **"modified"**, respectively.
This will replace usage of the terms "new" (except to refer to newly added files or newly added phpcs messages for reporting), "old", "base" (except to refer to git base), "previous", "changed", and "orig" in most contexts.

Use "unmodified" > "modified" terms

---

PhpcsChanged/Cli.php

When no `--cache` flag is provided, we don't need to print any output on whether a cached info for a file was found or not. It should improve the readability of the debug output.

Move the debug info on (not)using cache behind isCachingEnabled check

---

PhpcsChanged/CacheManager.php
PhpcsChanged/Cli.php
README.md
bin/phpcs-changed
tests/CacheManagerTest.php
tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

Passing in the `--warning-severity` and `--error-severity` flags to phpcs is rather straightforward, however we need to take into consideration the caching layer.
It currently uses the standard as a cache key, and it definitelly should take into consideration different severity settings. To make sure the existing cache is backward compatible with the one created by previous version of phpcs-changed, we can map the default severity ('5') to a standard run w/o severity settings.
I _think_ that simply appending the warning and error severity value to the standard used in the key can make it work.
fixes #56

First pass at passing in error and warning severity to phpcs

---

PhpcsChanged/GitWorkflow.php
PhpcsChanged/SvnWorkflow.php

This replaces the JS-style variable interpolation `${var}` with PHP-style `{$var}` since the former is deprecated.
Fixes https://github.com/sirbrillig/phpcs-changed/issues/62

Replace JS-style var interpolation with PHP-style

---

tests/GitWorkflowTest.php
tests/SvnWorkflowTest.php

Dynamic properties are deprecated in PHP 8.2

Add explicit properties to GitWorkflowTest/SvnWorkflowTest

---

PhpcsChanged/GitWorkflow.php
tests/GitWorkflowTest.php

When referencing a file in the remote repository, git requires that you specify the full path to the file.
For example, if you are in the root of a repository and run the following commands:
```
> cd foo/bar/
> git show HEAD:file.php
> echo $?
128
```
This will return an error because it can't find a file with a relative path. Instead, you can run the command with the full path to the file relative to the repo root:
```
> cd foo/bar/
> git show HEAD:$(git ls-files --full-name file.php)
> echo $?
0
```
For the `git show` command, `phpcs-changed` already does this thanks to the work done in https://github.com/sirbrillig/phpcs-changed/pull/18. However, the `git cat-file` command, added later in https://github.com/sirbrillig/phpcs-changed/pull/28 does not use that strategy, which means it …

Use full path command for git cat-file command
